### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sharewax** [spoter/spoter-mods#13]
Hello.
I've seen in the logs the next thing
```
2018-06-25 01:14:21.186: INFO: DEBUG[mods_gui]:
2018-06-25 01:14:21.187: INFO: gui.mods.mod_marksongunextended.onBattleEvents(Avatar, Avatar, [{eventType: 1, targetID: 21817120, details: 1778391
3999L, count: 1}])
2018-06-25 01:14:21.187: INFO: [START:]----------------
2018-06-25 01:14:21.187: INFO: Traceback (most recent call last):
2018-06-25 01:14:21.188: INFO:   File "hru-hru", line 108, in log
2018-06-25 01:14:21.188: INFO:   File "hru-hru", line 1167, in onBattleEvents
2018-06-25 01:14:21.188: INFO:   File "hru-hru", line 550, in <A8>(؈
2018-06-25 01:14:21.188: INFO: <ED> <9A>ݷ<B6>{<AA>^D<C0>){<EA><B1>
2018-06-25 01:14:21.188: INFO:   File "hru-hru", line 796, in <D5>^L<FA><DB>^E<9E>)<FD><B2>
2018-06-25 01:14:21.188: INFO:   File "hru-hru", line 607, in getColor
2018-06-25 01:14:21.189: INFO: IndexError: list index out of range
2018-06-25 01:14:21.189: INFO: [END:]------------------
2018-06-25 01:14:21.576: INFO: DEBUG[mods_gui]:
2018-06-25 01:14:21.576: INFO: gui.mods.mod_marksongunextended.onBattleEvents(Avatar, Avatar, [{eventType: 1, targetID: 21817117, details: 1238165
0447L, count: 1}])
2018-06-25 01:14:21.576: INFO: [START:]----------------
2018-06-25 01:14:21.576: INFO: Traceback (most recent call last):
2018-06-25 01:14:21.577: INFO:   File "hru-hru", line 108, in log
2018-06-25 01:14:21.577: INFO:   File "hru-hru", line 1167, in onBattleEvents
2018-06-25 01:14:21.577: INFO:   File "hru-hru", line 550, in <A8>(؈
2018-06-25 01:14:21.577: INFO: <ED> <9A>ݷ<B6>{<AA>^D<C0>){<EA><B1>
2018-06-25 01:14:21.577: INFO:   File "hru-hru", line 796, in <D5>^L<FA><DB>^E<9E>)<FD><B2>
2018-06-25 01:14:21.577: INFO:   File "hru-hru", line 607, in getColor
2018-06-25 01:14:21.577: INFO: IndexError: list index out of range
2018-06-25 01:14:21.578: INFO: [END:]------------------
2018-06-25 01:14:41.393: INFO: DEBUG[mods_gui]:
2018-06-25 01:14:41.394: INFO: gui.mods.mod_marksongunextended.onBattleEvents(Avatar, Avatar, [{eventType: 0, targetID: 21817139, details: 0L, cou
nt: 1}])
2018-06-25 01:14:41.394: INFO: [START:]----------------
2018-06-25 01:14:41.394: INFO: Traceback (most recent call last):
2018-06-25 01:14:41.394: INFO:   File "hru-hru", line 108, in log
2018-06-25 01:14:41.394: INFO:   File "hru-hru", line 1167, in onBattleEvents
2018-06-25 01:14:41.395: INFO:   File "hru-hru", line 550, in <A8>(؈
2018-06-25 01:14:41.395: INFO: <ED> <9A>ݷ<B6>{<AA>^D<C0>){<EA><B1>
2018-06-25 01:14:41.395: INFO:   File "hru-hru", line 796, in <D5>^L<FA><DB>^E<9E>)<FD><B2>
2018-06-25 01:14:41.395: INFO:   File "hru-hru", line 607, in getColor
2018-06-25 01:14:41.395: INFO: IndexError: list index out of range
2018-06-25 01:14:41.395: INFO: [END:]------------------
2018-06-25 01:15:03.589: INFO: DEBUG[mods_gui]:
2018-06-25 01:15:03.590: INFO: gui.mods.mod_marksongunextended.onBattleEvents(Avatar, Avatar, [{eventType: 6, targetID: 21817140, details: 16842255L, count: 1}])
2018-06-25 01:15:03.590: INFO: [START:]----------------
2018-06-25 01:15:03.590: INFO: Traceback (most recent call last):
2018-06-25 01:15:03.591: INFO:   File "hru-hru", line 108, in log
2018-06-25 01:15:03.591: INFO:   File "hru-hru", line 1167, in onBattleEvents
2018-06-25 01:15:03.591: INFO:   File "hru-hru", line 550, in <A8>(؈
2018-06-25 01:15:03.591: INFO: <ED> <9A>ݷ<B6>{<AA>^D<C0>){<EA><B1>
2018-06-25 01:15:03.591: INFO:   File "hru-hru", line 796, in <D5>^L<FA><DB>^E<9E>)<FD><B2>
2018-06-25 01:15:03.592: INFO:   File "hru-hru", line 607, in getColor
2018-06-25 01:15:03.592: INFO: IndexError: list index out of range
2018-06-25 01:15:03.592: INFO: [END:]------------------
2018-06-25 01:15:12.986: INFO: DEBUG[mods_gui]:
2018-06-25 01:15:12.987: INFO: gui.mods.mod_marksongunextended.onBattleEvents(Avatar, Avatar, [{eventType: 6, targetID: 21817140, details: 16842255L, count: 1}])
2018-06-25 01:15:12.987: INFO: [START:]----------------
2018-06-25 01:15:12.987: INFO: Traceback (most recent call last):
2018-06-25 01:15:12.988: INFO:   File "hru-hru", line 108, in log
2018-06-25 01:15:12.988: INFO:   File "hru-hru", line 1167, in onBattleEvents
2018-06-25 01:15:12.988: INFO:   File "hru-hru", line 550, in <A8>(؈
2018-06-25 01:15:12.988: INFO: <ED> <9A>ݷ<B6>{<AA>^D<C0>){<EA><B1>
2018-06-25 01:15:12.988: INFO:   File "hru-hru", line 796, in <D5>^L<FA><DB>^E<9E>)<FD><B2>
2018-06-25 01:15:12.988: INFO:   File "hru-hru", line 607, in getColor
2018-06-25 01:15:12.989: INFO: IndexError: list index out of range
2018-06-25 01:15:12.989: INFO: [END:]------------------
2018-06-25 01:15:20.368: INFO: DEBUG[mods_gui]:
2018-06-25 01:15:20.368: INFO: gui.mods.mod_marksongunextended.onBattleEvents(Avatar, Avatar, [{eventType: 2, targetID: 21817140, details: 10804592143L, count: 1}])
2018-06-25 01:15:20.368: INFO: [START:]----------------
2018-06-25 01:15:20.369: INFO: Traceback (most recent call last):
2018-06-25 01:15:20.369: INFO:   File "hru-hru", line 108, in log
2018-06-25 01:15:20.370: INFO:   File "hru-hru", line 1167, in onBattleEvents
2018-06-25 01:15:20.370: INFO:   File "hru-hru", line 550, in <A8>(؈
2018-06-25 01:15:20.370: INFO: <ED> <9A>ݷ<B6>{<AA>^D<C0>){<EA><B1>
2018-06-25 01:15:20.370: INFO:   File "hru-hru", line 796, in <D5>^L<FA><DB>^E<9E>)<FD><B2>
2018-06-25 01:15:20.371: INFO:   File "hru-hru", line 607, in getColor
2018-06-25 01:15:20.371: INFO: IndexError: list index out of range
2018-06-25 01:15:20.371: INFO: [END:]------------------
```
Is it fixable or no? Thank you.

**Comment by sharewax** [comment]
currently is working as expected.
