### ISSUE TITLE
MoE extended mod does not work with 1.1.0

### ISSUE THREAD

**Issue by Willster419** [spoter/spoter-mods#16]
Hello,
In testing MoE, it does not work in battle, it spamms the python log:
2018-09-03 13:44:38.448: ERROR: Traceback (most recent call last):
2018-09-03 13:44:38.448: ERROR:   File "scripts/client/game.py", line 564, in handleKeyEvent
2018-09-03 13:44:38.449: ERROR:   File "scripts/client/gui/InputHandler.py", line 30, in handleKeyEvent
2018-09-03 13:44:38.449: ERROR:   File "scripts/common/Event.py", line 44, in __call__
2018-09-03 13:44:38.449: ERROR:   File "hru-hru", line 809, in èĒ"ퟬ�薨܍
2018-09-03 13:44:38.449: ERROR:   File "hru-hru", line 1089, in setupSize
2018-09-03 13:44:38.449: ERROR:   File "hru-hru", line 1032, in updateObject
2018-09-03 13:44:38.449: ERROR: KeyError: 'Panel'
2018-09-03 13:44:38.652: ERROR: [EXCEPTION] (scripts/common/Event.py, 46):
Traceback (most recent call last):
  File "scripts/common/Event.py", line 44, in __call__
  File "hru-hru", line 797, in èĒ"ퟬ�薨܍
  File "hru-hru", line 1089, in setupSize
  File "hru-hru", line 1032, in updateObject
KeyError: 'Panel'

Also, the archive comes with gambiter.guiflash_0.2.5.1, but gambiter.guiflash_0.2.5.2 is available

**Comment by spoter** [comment]
https://github.com/GambitER/GUIFlash
gambiter.guiflash_0.2.5.2 - is not a valid version

**Comment by Willster419** [comment]
using 0.2.5.1 it does not work eithor

**Comment by Willster419** [comment]
You can replicate the error with gambiter.guiflash_0.2.5.1, and load into a training room.
Please, can you fix the mod?
