### ISSUE TITLE
insignia monitor - g_apploader

### ISSUE THREAD

**Issue by elektrosmoker** [spoter/spoter-mods#47]
hy there,

still got this error when loading into game (using the 6days old "1.5.0 flash fix"):

2019-05-04 11:37:39.233: INFO: [SL_PRO] Skipped Script: mod_insigniamonitor.pyc
2019-05-04 11:37:39.233: INFO: 
2019-05-04 11:37:39.233: ERROR: [EXCEPTION] (<string>, 596):
Traceback (most recent call last):
  File "<string>", line 584, in _findValidMODs
  File "scripts/common/Lib/importlib/__init__.py", line 37, in import_module
  File "source\mod_insigniaMonitor.py", line 10, in <module>
ImportError: cannot import name g_appLoader

**Comment by spoter** [comment]
fix
