### ISSUE TITLE
attribute error with traceback

### ISSUE THREAD

**Issue by sharewax** [spoter/spoter-mods#48]
```
2019-05-04 00:47:46.152: INFO: DEBUG[mods_gui]:
2019-05-04 00:47:46.152: INFO: gui.mods.mod_spotted_extended_light.onBattleEvents(gui.mods.mod_mods_gui, Avatar, [{eventType: 0, targetID: 11518747, details: 0L, count: 1}])
2019-05-04 00:47:46.152: INFO: [START:]----------------
2019-05-04 00:47:46.152: INFO: Traceback (most recent call last):
2019-05-04 00:47:46.152: INFO:   File "hru-hru", line 109, in log
2019-05-04 00:47:46.153: INFO:   File "source\mod_spotted_extended_light.py", line 240, in onBattleEvents
2019-05-04 00:47:46.153: INFO:   File "source\mod_spotted_extended_light.py", line 221, in post_message
2019-05-04 00:47:46.153: INFO: AttributeError: '_VisibilityExtra' object has no attribute 'getDamage'
2019-05-04 00:47:46.153: INFO: [END:]------------------
2019-05-04 00:49:44.763: INFO: DEBUG[mods_gui]:
2019-05-04 00:49:44.763: INFO: gui.mods.mod_spotted_extended_light.onBattleEvents(gui.mods.mod_mods_gui, Avatar, [{eventType: 0, targetID: 11518752, details: 0L, count: 1}])
2019-05-04 00:49:44.763: INFO: [START:]----------------
2019-05-04 00:49:44.763: INFO: Traceback (most recent call last):
2019-05-04 00:49:44.763: INFO:   File "hru-hru", line 109, in log
2019-05-04 00:49:44.763: INFO:   File "source\mod_spotted_extended_light.py", line 240, in onBattleEvents
2019-05-04 00:49:44.763: INFO:   File "source\mod_spotted_extended_light.py", line 221, in post_message
2019-05-04 00:49:44.763: INFO: AttributeError: '_VisibilityExtra' object has no attribute 'getDamage'
2019-05-04 00:49:44.764: INFO: [END:]------------------
```

Can you check it? Found in python.log

**Comment by spoter** [comment]
check now

**Comment by sharewax** [comment]
Needs to reopen.
```
2019-05-10 01:00:14.168: INFO: DEBUG[mods_gui]:
2019-05-10 01:00:14.169: INFO: gui.mods.mod_spotted_extended_light.onBattleEvents(gui.mods.mod_mods_gui, Avatar, [{eventType: 0, targetID: 15513265, details: 0L, count: 1}])
2019-05-10 01:00:14.169: INFO: [START:]----------------
2019-05-10 01:00:14.169: INFO: Traceback (most recent call last):
2019-05-10 01:00:14.169: INFO:   File "hru-hru", line 109, in log
2019-05-10 01:00:14.170: INFO:   File "source\mod_spotted_extended_light.py", line 241, in onBattleEvents
2019-05-10 01:00:14.170: INFO:   File "source\mod_spotted_extended_light.py", line 222, in post_message
2019-05-10 01:00:14.170: INFO: AttributeError: '_VisibilityExtra' object has no attribute 'getDamage'
2019-05-10 01:00:14.170: INFO: [END:]------------------
2019-05-10 01:00:37.383: INFO: DEBUG[mods_gui]:
2019-05-10 01:00:37.383: INFO: gui.mods.mod_spotted_extended_light.onBattleEvents(gui.mods.mod_mods_gui, Avatar, [{eventType: 0, targetID: 15513287, details: 0L, count: 1}])
2019-05-10 01:00:37.383: INFO: [START:]----------------
2019-05-10 01:00:37.383: INFO: Traceback (most recent call last):
2019-05-10 01:00:37.383: INFO:   File "hru-hru", line 109, in log
2019-05-10 01:00:37.383: INFO:   File "source\mod_spotted_extended_light.py", line 241, in onBattleEvents
2019-05-10 01:00:37.384: INFO:   File "source\mod_spotted_extended_light.py", line 222, in post_message
2019-05-10 01:00:37.384: INFO: AttributeError: '_VisibilityExtra' object has no attribute 'getDamage'
2019-05-10 01:00:37.384: INFO: [END:]------------------
```

Happens when I saw the battle from the other tank. No amount of assist was shown. spoter.spotted_extended_light_4.06.wotmod
