### ISSUE TITLE
gui.mods, mod_playerpanelsapi.pyc error

### ISSUE THREAD

**Issue by Arkhorse** [spoter/spoter-mods#49]
```
2019-05-05 01:34:26.844: WARNING: [WARNING] (scripts/client/gui/mods/__init__.py, 72): There is problem while import gui mod ('gui.mods', 'mod_playerpanelsapi.pyc')
2019-05-05 01:34:26.846: ERROR: [EXCEPTION] (scripts/client/gui/mods/__init__.py, 74):
Traceback (most recent call last):
  File "scripts/client/gui/mods/__init__.py", line 67, in _findValidMODs
  File "scripts/common/Lib/importlib/__init__.py", line 37, in import_module
  File "mod_playerpanelsapi", line 1, in <pjorion_obfuscated>
ImportError: cannot import name g_appLoader

```

Shouldnt g_appLoader now be IApploader?

**Comment by spoter** [comment]
Thats not my mod.
In my mods_gui try inject.g_appLoader
