### ISSUE TITLE
MoE: ZeroDivisionError

### ISSUE THREAD

**Issue by CH4MPi** [spoter/spoter-mods#59]
2019-06-12 13:05:59.529: INFO: DEBUG[mods_gui]:
2019-06-12 13:05:59.529: INFO: gui.mods.mod_marksongunextended.getCurrentHangarData(gui.mods.mod_marksongunextended)
2019-06-12 13:05:59.529: INFO: [START:]----------------
2019-06-12 13:05:59.529: INFO: Traceback (most recent call last):
2019-06-12 13:05:59.529: INFO:   File "hru-hru", line 126, in log
2019-06-12 13:05:59.529: INFO:   File "source\mod_marksOnGunExtended.py", line 545, in getCurrentHangarData
2019-06-12 13:05:59.529: INFO:   File "source\mod_marksOnGunExtended.py", line 630, in requestCurData
2019-06-12 13:05:59.529: INFO: ZeroDivisionError: float division by zero
2019-06-12 13:05:59.529: INFO: [END:]------------------

**Comment by spoter** [comment]
Couldn't make the same error again.

**Comment by CH4MPi** [comment]
i can't reproduce it, but i'll inform you when it happens again.
