### ISSUE TITLE
Mod mod_marksOnGunExtended doesn't work after 1.11.0.0 updating.

### ISSUE THREAD

**Issue by pechenkin** [spoter/spoter-mods#70]
Hello everyone! Mod marksOnGunExtended doesn't work after 1.11.0.0 updating.

`2020-12-09 01:07:21.357: INFO: [START:]----------------
2020-12-09 01:07:21.357: INFO: Traceback (most recent call last):
2020-12-09 01:07:21.357: INFO:   File "hru-hru", line 131, in log
2020-12-09 01:07:21.357: INFO:   File "source\mod_marksOnGunExtended.py", line 1577, in getRequiredLibraries
2020-12-09 01:07:21.357: INFO: TypeError: can only concatenate list (not "tuple") to list
2020-12-09 01:07:21.357: INFO: [END:]------------------`

Apparently getRequiredLibraries() returns now list instead tuples. Here is the solution that works (for me):
`diff --git a/mod_marksOnGunExtended/source/mod_marksOnGunExtended.py b/mod_marksOnGunExtended/source/mod_marksOnGunExtended.py
old mode 100644
new mode 100755
index fe11b10..a26f999
--- a/mod_marksOnGunExtended/source/mod_marksOnGunExtended.py
+++ b/mod_marksOnGunExtended/source/mod_marksOnGunExtended.py
@@ -1574,7 +1574,7 @@ def makeHeaderVO(func, *args):
 @inject.hook(LobbyEntry, '_getRequiredLibraries')
 @inject.log
 def getRequiredLibraries(func, *args):
-    return func(*args) + ('marksOnGun.swf',)
+    return func(*args) + ['marksOnGun.swf', '']
 
 
 BigWorld.MoESetupSize = flash.setupSize`
Best regards!

**Comment by sashamilutka** [comment]
Обновы не будет?

**Comment by dkruben** [comment]
Fixed :)

**Comment by sashamilutka** [comment]
Как можно изменить данный путь ("backgroundImage": "../maps/icons/quests/inBattleHint.png",) так, что бы можно было свой фон преминять. [IMG]http://ipic.su/img/img7/fs/shot_002.1609649351.jpg[/IMG]

**Comment by dkruben** [comment]
@sashamilutka if in configs folder 
"backgroundImage": '../../configs/spoter/marksOnGunExtended/[**backgroudname**].png',
